### ISSUE TITLE
連結首頁的圖到教材連結

### ISSUE THREAD

**Issue by nonumpa** [nics-tw/resilience-material#10]
## 需求

易用性、可維護性、高可用性點擊後要能連結到對應的教材

<img width="1000" alt="截圖 2024-11-28 下午5 12 19" src="https://github.com/user-attachments/assets/784fd37c-9a81-4309-9254-dbe29c3c5281">

## 問題

目前「易用性、可維護性、高可用性」在主目錄「共通性教材」底下，首頁的圖與教材頁面子目錄直接連結會有點怪，建議改一下教材頁面目錄排版的樣子

目前教材排版：
<img width="500" alt="from" src="https://github.com/user-attachments/assets/8ac22912-3630-4a82-a565-0e806d2beb5b">

想要改排成這樣：
<img width="500" alt="to" src="https://github.com/user-attachments/assets/3b3d4e45-f504-46c8-a50c-78d29c94f804">

@keroro-nics @Luxame @IK-Ngoo

**Comment by keroro-nics** [comment]
我贊成新的排版規劃
